### PR TITLE
docs: replace go build with go install

### PR DESCRIPTION
**Pull request by bashbunni**
## Changes made:
Changed directives for building from source to use `go install` instead of `go build` so melt is added to GOPATH. Otherwise, the user would have to manually add the binary to their GOPATH

### CODE REVIEW

**Comment by bashbunni** [comment]
Want to make some more changes to the README before merging...

**Comment by jon4hz** [comment]
`go install github.com/charmbracelet/melt/cmd/melt@latest` would also work to install it directly without cloning the repo first

**Comment by bashbunni** [comment]
Ok I think this is enough for now. Didn't change too much just added some installation + build instructions.

**Comment by bashbunni** [comment]
Ah actually pushed old changes -_- let me fix it and I'll ping you

**Comment by bashbunni** [comment]
ok it's good now, we can discuss it later this morning :)

**Pull request merged**
